### ISSUE TITLE
Help documentation in modeller for method "append" is wrong

### ISSUE THREAD

**Issue by LLdaniel** [Xyna-Factory/xyna-process-modeller#6]
#### Context
Found in modeller version 1.1.19.4

#### Problem description
The modeller help documentation (right menu bar) states that the method "append" should be used in this way:
`append(DT, DT[]): DT[] ALT+a`

This seems to be a wrong documentation because using it this way will lead to deployment issues.

#### Expectation
Documentation should state that method "append" should be used in the following way:
`append(DT[], DT): DT[] ALT+a`

#### working example
This is a working example without deployment issues.
<img width="944" alt="appendDocumentation" src="https://user-images.githubusercontent.com/41345639/203585286-9e288964-1f2b-49ac-b470-b948ba141da3.PNG">

**Comment by TorbenSiegismund-GIP** [comment]
Mir scheint das Problem gelöst zu sein.
![Hilfe](https://github.com/Xyna-Factory/xyna-process-modeller/assets/127193495/aa584072-9f84-40d6-9f21-1073377f23dc)
